# マウス操作を有効にする
set-option -g mouse on

# スクロールホイールの動作を設定
bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind-key -n WheelDownPane select-pane -t= \; send-keys -M

# ターミナルエミュレータ経由でのクリップボード同期を有効化
set -s set-clipboard on

# 選択が終わった時に自動でクリップボードにコピーする
set -s copy-command 'pbcopy'

# マウスドラッグでコピーした際に、コピーモードを終了しない
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "pbcopy" 

# Viモードでの選択をクリップボードにコピー
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"

# ステータスバーを有効にする
set-option -g status on

# 更新間隔（秒）
set-option -g status-interval 5

# 左側：セッション名を表示
set-option -g status-left-length 20
set-option -g status-left "[#S] "

# 右側：カレントディレクトリ と Gitブランチを表示
set-option -g status-right-length 100
set-option -g status-right " #(~/.config/tmux/branch.sh #{pane_current_path})"
