core:
  trash:
    strategy: xdg
    home_fallback: false
    forbidden_paths:
    - $HOME/.local/share/Trash
    - $HOME/.trash
    - $XDG_DATA_HOME/Trash
    - /tmp/Trash
    - /var/tmp/Trash
    - $HOME/.gomi
    - /
    - /etc
    - /usr
    - /var
    - /bin
    - /sbin
    - /lib
    - /lib64
  restore:
    confirm: true
    verbose: true
  permanent_delete:
    enable: false
ui:
  preview:
    directory_command: ls -GF -1 -A --color=always
